### ISSUE TITLE
Scan2Deploy VS dlstager

### ISSUE THREAD

**Issue by acaliaro** [datalogic/dl_config#1]
Hi @codybrookshear 

I have there questions for you

**Question 1:**

I create a QRCODE with this json:

```
{
	"layout": {
		"description": "Procedura di enroll",
		"enroll": false
	},
	"global": {
		"action": "close"
	},
	"settings": {
		"debug-bridge": true,
		"lock-screen": false,
		"status-bar": false,
		"navigation-bar": false
	},	
	"$schema": "https://raw.githubusercontent.com/datalogic/scan2deploy-android-schema/master/schema.json"
}

```
I read the QRCODE using DLSTAGER on a Android Joya Touch and it seems settings are applied (maybe lock-screen is not applied but otheres are).

Why DLSTAGER works without Device Owner but Scan2Deploy require to be Device Owner?

**Question 2:**

Then, I would like to use 

https://datalogic.github.io/scan2deploy/android#call-startactivity

But the java code

```
Intent launchIntent = getPackageManager().getLaunchIntentForPackage("com.datalogic.scan2deploy");
launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
launchIntent.putExtra("data", "Bm9uiYc//NWOnA0ZtIrgJ/qy0DCvHR+a1XwUz1sTne8s0KEM9ANwTS0XD4NbIOf/hV0+MM7cOFiZMbUDtO1L4sb4vnJluFbQOEM3phIuCRiBuMtpnh85");
getApplicationContext().startActivity(launchIntent);
```

open scan2deploy that needs to be Device Owner... is not possible to send "data" to DLSTAGER instead of Scan2Deploy?

**Question 3:**
Which is the official / preferred tool between Scan2Deploy and DLSTAGER to execute json commands?

Thanks

**Comment by acaliaro** [comment]
Hi @codybrookshear .

About quetion 1 and 2, I have solved using this code:

```
        Intent launchIntent = MyCustomApplication.getAppContext().getPackageManager().getLaunchIntentForPackage("com.datalogic.android.dlstager");
        if(launchIntent == null)
            throw  new Exception(MyCustomApplication.getAppContext().getString(R.string.errore_gestione_comando));

        launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        launchIntent.putExtra("data", "~0101" + data);
        MyCustomApplication.getAppContext().getApplicationContext().startActivity(launchIntent);
```

It's not "official" (I have not found documentation about it) but it seems to work...

Do you have some feedbacks about question 3?
Thanks
Alessandro

**Comment by codybrookshear** [comment]
Hi Alessandro,

My apologies for taking so long to get back to you.

Scan2Deploy is certainly the preferred tool going forward. DL-Stager is provided on Joya devices for existing customers that are already used to using DL-Stager and have already created barcodes that rely on DL-Stager.

I was able to confirm myself on a Joya Touch A6 that with the [latest JoyaTouch A6 firmware 3.03.04 Android 8.1](https://developer.datalogic.com/mobile-computers/products/joya-touch-a6/android/firmware), Scan2Deploy is able to be used without being Device Owner (no special steps required at the "Hi There" screen after factory reset). If that was previously a road block for you in using Scan2Deploy, that is no longer an issue.

Thank you,
Cody
